---
kind: pipeline
name: molecule
workspace:
  path: veselahouba.bareos

environment:
  DISTROS_SERVER: ubuntu1804 ubuntu2004 debian11 debian10 debian9
  DISTROS_CLIENT: ubuntu1604 ubuntu1804 ubuntu2004 debian9 debian10 debian11

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run
      - name: sysfs
        path: /sys/fs/cgroup

volumes:
  - name: dockersock
    temp: {}
  - name: sysfs
    host:
      path: /sys/fs/cgroup

steps:
  - name: Lint
    image: veselahouba/molecule
    commands:
      - shellcheck_wrapper
      - flake8
      - yamllint .
      - ansible-lint

  - name: Molecule test
    image: veselahouba/molecule
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run
      - name: sysfs
        path: /sys/fs/cgroup
    commands:
      - sleep 5
      - docker ps -a
      - ansible --version
      - molecule --version
      # Loop through all servers and client combinations
      - |
        for MOLECULE_DISTRO_SERVER in $${DISTROS_SERVER}; do
          for MOLECULE_DISTRO_CLIENT in $${DISTROS_CLIENT}; do
            export MOLECULE_DISTRO_SERVER
            export MOLECULE_DISTRO_CLIENT
            molecule test --all
          done
        done

  - name: Slack notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: ci-cd
      template: >
        Molecule for `{{build.branch}}` failed.
        {{build.link}}
    when:
      status:
        - failure
---
kind: pipeline
name: release
depends_on:
  - molecule
trigger:
  event:
    - tag
steps:
  - name: publish
    image: veselahouba/molecule
    environment:
      GALAXY_API_KEY:
        from_secret: GALAXY_API_KEY
    commands:
      - >
        ansible-galaxy role import --api-key $${GALAXY_API_KEY}
        $${DRONE_REPO_OWNER} $${DRONE_REPO_NAME}

  - name: Slack notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: ci-cd
      template: >
        {{#success build.status}}
          Publish for `{{build.tag}}` succeeded.
          {{build.link}}
        {{else}}
          Publish for `{{build.tag}}` failed.
          {{build.link}}
        {{/success}}
    when:
      status:
        - success
        - failure
