---
dependency:
  name: galaxy
driver:
  name: hetznercloud
platforms:
  - name: ${REPO_NAME}-${OS_VERSION}-${REF}-server
    server_type: cx11
    image: ${MOLECULE_IMAGE}
    custom_ssh_key_name: molecule.admin
    groups:
      - server
  - name: ${REPO_NAME}-${OS_VERSION}-${REF}-client
    server_type: cx11
    image: ${MOLECULE_IMAGE}
    custom_ssh_key_name: molecule.admin
    groups:
      - client
provisioner:
  name: ansible
verifier:
  name: testinfra
